### PR TITLE
Update Jenkins Security Scan action

### PR DESCRIPTION
**Pull request by strangelookingnerd**
In order to unify the actions configuration this PR will

- [x] Removes the hard-coded `java-version` in order to rely on the default
- [ ] Adds a `java-cache` configuration to speed-up the actions buld time
- [ ] Adds `permissions` allowing the action to create security issues
- [ ] Removes non-existant target `branches`

_Please note this PR was created semi-automatically. If you find any issue with it, don't hesitate to ping me._
_See discussion in https://github.com/jenkinsci/asm-api-plugin/pull/36_

### Testing done

Awaiting run of the action to verify the changes...

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by sbobin — APPROVED** [review]
LGTM. Thanks!

**Comment by sbobin** [comment]
Hi @strangelookingnerd !

Why did 2 checks fail above, please? I thought that maybe my code does not build with Java 21 but it seems to be something else. What does this error mean: Could not fetch revision from repository: org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator::https://api.github.com::jenkinsci::mathworks-polyspace-plugin and branch: PR-6?

Thanks!

Stephane

**Comment by strangelookingnerd** [comment]
> Hi @strangelookingnerd !
> 
> Why did 2 checks fail, please? I thought that maybe my code does not build with Java 21 but it seems to be something else. What does this error mean: Could not fetch revision from repository: org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator::https://api.github.com::jenkinsci::mathworks-polyspace-plugin and branch: PR-6?
> 
> Thanks!
> 
> Stephane

This could just be an issue from ci.jenkins.io - you may want to re-running the check as this usually resolves these kind of issues.

**Comment by sbobin** [comment]
Good to know. Rerun worked. Thanks!

**Pull request merged**
